/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...notFound]': RouteRecordInfo<'/[...notFound]', '/:notFound(.*)', { notFound: ParamValue<true> }, { notFound: ParamValue<false> }>,
    '/batch-processing': RouteRecordInfo<'/batch-processing', '/batch-processing', Record<never, never>, Record<never, never>>,
    '/change-password': RouteRecordInfo<'/change-password', '/change-password', Record<never, never>, Record<never, never>>,
    '/comment-emotion': RouteRecordInfo<'/comment-emotion', '/comment-emotion', Record<never, never>, Record<never, never>>,
    '/comment-location': RouteRecordInfo<'/comment-location', '/comment-location', Record<never, never>, Record<never, never>>,
    '/comment-topic': RouteRecordInfo<'/comment-topic', '/comment-topic', Record<never, never>, Record<never, never>>,
    '/comment-wordcloud': RouteRecordInfo<'/comment-wordcloud', '/comment-wordcloud', Record<never, never>, Record<never, never>>,
    '/document-import': RouteRecordInfo<'/document-import', '/document-import', Record<never, never>, Record<never, never>>,
    '/information-extraction': RouteRecordInfo<'/information-extraction', '/information-extraction', Record<never, never>, Record<never, never>>,
    '/keyword-summary': RouteRecordInfo<'/keyword-summary', '/keyword-summary', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/operation-log': RouteRecordInfo<'/operation-log', '/operation-log', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/result-display': RouteRecordInfo<'/result-display', '/result-display', Record<never, never>, Record<never, never>>,
    '/text-preprocess': RouteRecordInfo<'/text-preprocess', '/text-preprocess', Record<never, never>, Record<never, never>>,
    '/user': RouteRecordInfo<'/user', '/user', Record<never, never>, Record<never, never>>,
    '/video-trend': RouteRecordInfo<'/video-trend', '/video-trend', Record<never, never>, Record<never, never>>,
  }
}
